### PR TITLE
Create static library for libndt7

### PR DESCRIPTION
**Pull request by BaiiYuan**
* Split `libndt7.hpp` into `libndt7.h` and `libndt7.cc`.
* Build the static library `libndt7.a`.
* Update the cmake file to install the static library and header.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40)

### CODE REVIEW

**Comment by BaiiYuan** [comment]
This PR should be merged after https://github.com/m-lab/ndt7-client-cc/pull/38.

**Review by stephen-soltesz — COMMENTED** [review]
@BaiiYuan is it possible to split this into two PRs? I see there is code reorganization and code changes within the reorganized logic. Ideally, these would be two PRs so I don't miss any logic changes. Is this possible?

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-:-Nshr5esDZCzGIzSAtKc:bgr21e2)* status: 0 of 1 approvals obtained

**Comment by BaiiYuan** [comment]
Noted.

I created another PR https://github.com/m-lab/ndt7-client-cc/pull/41 for logical changes and remove the file reformat part to reduce the number of line changes in `single_include/libndt7.hpp`.

This PR include https://github.com/m-lab/ndt7-client-cc/pull/41. I will rebase it later.

**Comment by BaiiYuan** [comment]
This CL is rebased and passes checks.

Hi @stephen-soltesz , please help me review it :D

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40)* status: 0 of 1 approvals obtained (waiting on @BaiiYuan)

___
*[`CMakeLists.txt` line 167 at r4](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-NsmgU1OCBxlKg7USrtd:-NsmgU1OCBxlKg7USrte:b-8rsccs) ([raw file](https://github.com/m-lab/ndt7-client-cc/blob/40b986c94d628abd2f56066f8ccd261f393ea32d/CMakeLists.txt#L167)):*
> ```CMake
> file(REMOVE ${MK_LIBNDT7_LIBRARY_SOURCE})
> foreach(SOURCE IN ITEMS
>   include/libndt7/preamble.hpp
> ```

nit: indenting here is different than above `foreach`. Please adjust one or the other to match. (I prefer the above, since it's easier to distinguish between for loop and inner content of loop.)
___
*[`include/libndt7/libndt7.h` line 52 at r4](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-NsmhZEl9Whfqp4usaSW:-NsmhZEl9Whfqp4usaSX:b-77umiz) ([raw file](https://github.com/m-lab/ndt7-client-cc/blob/40b986c94d628abd2f56066f8ccd261f393ea32d/include/libndt7/libndt7.h#L52)):*
> ```objc
> struct adl_serializer;
> 
> template <template <typename U, typename V, typename... Args> class ObjectType =
> ```

Is this new logic? Where did this come from originally? I don't see a corresponding removal.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40)* status: 0 of 1 approvals obtained (waiting on @BaiiYuan)

___
*[`include/libndt7/libndt7.h` line 52 at r4](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-NsmhZEl9Whfqp4usaSW:-NsmxznwAyfrHovn5NJi:b-rx28g0) ([raw file](https://github.com/m-lab/ndt7-client-cc/blob/40b986c94d628abd2f56066f8ccd261f393ea32d/include/libndt7/libndt7.h#L52)):*
<details><summary><i>Previously, BaiiYuan (Byron Lee) wrote…</i></summary><blockquote>

This part is copied from [here](https://github.com/m-lab/ndt7-client-cc/blob/main/third_party/github.com/nlohmann/json/json.hpp#L810-L846), which is the forward declaration of `nlohmann::json`.
</blockquote></details>

Why do we need to copy logic from json.hpp rather than include that file? My thought is that this confuses who is the code owner for this logic. Is there another way?

**Review by stephen-soltesz — COMMENTED** [review]
In that case, rather than copying code that we don't own into libndt7.h, I recommend vendoring `json_fwd.hpp` so we can rely on the upstream source as authoritative.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-:-NsnJBuf7QKD2bCWpCPA:b9osuzn)* status: 0 of 1 approvals obtained (waiting on @BaiiYuan)

**Comment by BaiiYuan** [comment]
> In that case, rather than copying code that we don't own into libndt7.h, I recommend vendoring json_fwd.hpp so we can rely on the upstream source as authoritative.

Done

**Review by stephen-soltesz — COMMENTED** [review]
I'm sorry for not being more specific. Third party sources belong in the third_party directory. With that change this will lgtm.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-:-NsrQLmwCL6Cu9Al0w_O:b-xaq8nf)* status: 0 of 1 approvals obtained (waiting on @BaiiYuan)

___
*[`include/libndt7/json_fwd.hpp` line 1 at r6](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-NsrPH6d4DWAJXViucvl:-NsrPH6d4DWAJXViucvm:b-a3i79d) ([raw file](https://github.com/m-lab/ndt7-client-cc/blob/ca64e478799a38c7274313aa292d7ba008c1b67a/include/libndt7/json_fwd.hpp#L1)):*
> ```cpp
> #ifndef INCLUDE_NLOHMANN_JSON_FWD_HPP_
> ```

Since this is a third party source file, please place this under the `third_party` directory for nlohmann/json. We don't want to mix first party and third party sources.

**Comment by BaiiYuan** [comment]
> Since this is a third party source file, please place this under the third_party directory for nlohmann/json. We don't want to mix first party and third party sources.

Thanks for the clear feedback. Done!

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-cc/40#-:-NssCjIZDCMGhjkPaHEa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
